  name: Publish Package

  on:
    workflow_run:
      workflows: ["Test and Build"]
      types:
        - completed

  jobs:
    publish:
      if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'

      runs-on: ubuntu-latest
      strategy:
        matrix:
          python: ["3.10", "3.11", "3.12"]

      permissions:
        id-token: write
        contents: read

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set Up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python }}

        - name: Install build deps
          run: |
            pip install tox tox-gh-actions wheel build twine

        - name: Test with tox
          run: |
            tox -e py${{ matrix.python }}-build_emp_orderly_types
    
        - name: Publish All Packages
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          run: |
            twine upload --repository pypi packages/emp_orderly_types/dist/*